### ISSUE TITLE
Implement sorting by review and filtering by tag

### ISSUE THREAD

**Issue by ltcptgeneral** [cse110-fa22-group29/cse110-fa22-group29#89]
Justification: Users will want to see their highest rated reviews when choosing a future meal and filter by tags to filter by cuisine type, location, or price. 

- Implement sorting on the homepage, where users can sort their reviews by rating to see the best reviews overall
- Implement filtering on the homepage where users can filter by tag name to see only reviews which contain this tag

**Comment by ltcptgeneral** [comment]
TBD: should tag filtering also perform substring matching, or will results be an exact matching of the query?

**Comment by KH-Cl** [comment]
> TBD: should tag filtering also perform substring matching, or will results be an exact matching of the query?

I think that would be a cool feature. I think it would just be a time thing. So if we could get it done within the sprint and to an helpful/useable degree
